import {Balthazar} from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

const balthazar = Balthazar({subsets : ['latin'], weight : '400'})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}) {
  return (
    //The Layout of this auth section is wrapped up inside Clerk Provider to provide authentication to pages included in this folder//
    <ClerkProvider >
        <html lang="en">
            <body className={`${balthazar.className}`} >{children}</body>
        </html>
    </ClerkProvider>
  )
}