import {Balthazar} from "next/font/google";
import "./globals.css"

const balthazar = Balthazar({subsets : ['latin'], weight : '400'})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body className={`${balthazar.className}`} >{children}</body>
    </html>
  )
}
